# Generated by Django 5.1.3 on 2024-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='image/')),
                ('comments', models.IntegerField(verbose_name='Количество коментариев')),
                ('like', models.IntegerField(verbose_name='Количество лайков')),
            ],
        ),
    ]
