# Generated by Django 5.1.3 on 2024-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя Сотрудника')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='image/')),
                ('gihub', models.URLField(verbose_name='Ссылка на Github')),
                ('twitter', models.URLField(verbose_name='Ссылка на Twitter')),
                ('facebook', models.URLField(verbose_name='Ссылка на facebook')),
                ('google', models.URLField(verbose_name='Ссылка на Google+')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
