# Generated by Django 5.1.3 on 2024-11-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='gihub',
            new_name='github',
        ),
    ]
