# Generated by Django 5.1.3 on 2024-11-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_gihub_personal_github'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Домашние ссылки'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
    ]
